apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oficina-api

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml

images:
  - name: oficina-api
    newName: ECR_REPOSITORY_URL
    newTag: latest
