// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/gabrielcamargo/oficina-api/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockVehicleRepository creates a new instance of MockVehicleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVehicleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVehicleRepository {
	mock := &MockVehicleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVehicleRepository is an autogenerated mock type for the VehicleRepository type
type MockVehicleRepository struct {
	mock.Mock
}

type MockVehicleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVehicleRepository) EXPECT() *MockVehicleRepository_Expecter {
	return &MockVehicleRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockVehicleRepository
func (_mock *MockVehicleRepository) Create(vehicle *entity.Vehicle) error {
	ret := _mock.Called(vehicle)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*entity.Vehicle) error); ok {
		r0 = returnFunc(vehicle)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVehicleRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockVehicleRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - vehicle *entity.Vehicle
func (_e *MockVehicleRepository_Expecter) Create(vehicle interface{}) *MockVehicleRepository_Create_Call {
	return &MockVehicleRepository_Create_Call{Call: _e.mock.On("Create", vehicle)}
}

func (_c *MockVehicleRepository_Create_Call) Run(run func(vehicle *entity.Vehicle)) *MockVehicleRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entity.Vehicle
		if args[0] != nil {
			arg0 = args[0].(*entity.Vehicle)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVehicleRepository_Create_Call) Return(err error) *MockVehicleRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVehicleRepository_Create_Call) RunAndReturn(run func(vehicle *entity.Vehicle) error) *MockVehicleRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockVehicleRepository
func (_mock *MockVehicleRepository) Delete(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVehicleRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockVehicleRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id string
func (_e *MockVehicleRepository_Expecter) Delete(id interface{}) *MockVehicleRepository_Delete_Call {
	return &MockVehicleRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockVehicleRepository_Delete_Call) Run(run func(id string)) *MockVehicleRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVehicleRepository_Delete_Call) Return(err error) *MockVehicleRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVehicleRepository_Delete_Call) RunAndReturn(run func(id string) error) *MockVehicleRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockVehicleRepository
func (_mock *MockVehicleRepository) FindAll() ([]*entity.Vehicle, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*entity.Vehicle
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*entity.Vehicle, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*entity.Vehicle); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Vehicle)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVehicleRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockVehicleRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *MockVehicleRepository_Expecter) FindAll() *MockVehicleRepository_FindAll_Call {
	return &MockVehicleRepository_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *MockVehicleRepository_FindAll_Call) Run(run func()) *MockVehicleRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVehicleRepository_FindAll_Call) Return(vehicles []*entity.Vehicle, err error) *MockVehicleRepository_FindAll_Call {
	_c.Call.Return(vehicles, err)
	return _c
}

func (_c *MockVehicleRepository_FindAll_Call) RunAndReturn(run func() ([]*entity.Vehicle, error)) *MockVehicleRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCustomerID provides a mock function for the type MockVehicleRepository
func (_mock *MockVehicleRepository) FindByCustomerID(customerID string) ([]*entity.Vehicle, error) {
	ret := _mock.Called(customerID)

	if len(ret) == 0 {
		panic("no return value specified for FindByCustomerID")
	}

	var r0 []*entity.Vehicle
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]*entity.Vehicle, error)); ok {
		return returnFunc(customerID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []*entity.Vehicle); ok {
		r0 = returnFunc(customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Vehicle)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(customerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVehicleRepository_FindByCustomerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCustomerID'
type MockVehicleRepository_FindByCustomerID_Call struct {
	*mock.Call
}

// FindByCustomerID is a helper method to define mock.On call
//   - customerID string
func (_e *MockVehicleRepository_Expecter) FindByCustomerID(customerID interface{}) *MockVehicleRepository_FindByCustomerID_Call {
	return &MockVehicleRepository_FindByCustomerID_Call{Call: _e.mock.On("FindByCustomerID", customerID)}
}

func (_c *MockVehicleRepository_FindByCustomerID_Call) Run(run func(customerID string)) *MockVehicleRepository_FindByCustomerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVehicleRepository_FindByCustomerID_Call) Return(vehicles []*entity.Vehicle, err error) *MockVehicleRepository_FindByCustomerID_Call {
	_c.Call.Return(vehicles, err)
	return _c
}

func (_c *MockVehicleRepository_FindByCustomerID_Call) RunAndReturn(run func(customerID string) ([]*entity.Vehicle, error)) *MockVehicleRepository_FindByCustomerID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockVehicleRepository
func (_mock *MockVehicleRepository) FindByID(id string) (*entity.Vehicle, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Vehicle
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*entity.Vehicle, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *entity.Vehicle); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Vehicle)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVehicleRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockVehicleRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id string
func (_e *MockVehicleRepository_Expecter) FindByID(id interface{}) *MockVehicleRepository_FindByID_Call {
	return &MockVehicleRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockVehicleRepository_FindByID_Call) Run(run func(id string)) *MockVehicleRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVehicleRepository_FindByID_Call) Return(vehicle *entity.Vehicle, err error) *MockVehicleRepository_FindByID_Call {
	_c.Call.Return(vehicle, err)
	return _c
}

func (_c *MockVehicleRepository_FindByID_Call) RunAndReturn(run func(id string) (*entity.Vehicle, error)) *MockVehicleRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByPlate provides a mock function for the type MockVehicleRepository
func (_mock *MockVehicleRepository) FindByPlate(plate string) (*entity.Vehicle, error) {
	ret := _mock.Called(plate)

	if len(ret) == 0 {
		panic("no return value specified for FindByPlate")
	}

	var r0 *entity.Vehicle
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*entity.Vehicle, error)); ok {
		return returnFunc(plate)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *entity.Vehicle); ok {
		r0 = returnFunc(plate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Vehicle)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(plate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVehicleRepository_FindByPlate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByPlate'
type MockVehicleRepository_FindByPlate_Call struct {
	*mock.Call
}

// FindByPlate is a helper method to define mock.On call
//   - plate string
func (_e *MockVehicleRepository_Expecter) FindByPlate(plate interface{}) *MockVehicleRepository_FindByPlate_Call {
	return &MockVehicleRepository_FindByPlate_Call{Call: _e.mock.On("FindByPlate", plate)}
}

func (_c *MockVehicleRepository_FindByPlate_Call) Run(run func(plate string)) *MockVehicleRepository_FindByPlate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVehicleRepository_FindByPlate_Call) Return(vehicle *entity.Vehicle, err error) *MockVehicleRepository_FindByPlate_Call {
	_c.Call.Return(vehicle, err)
	return _c
}

func (_c *MockVehicleRepository_FindByPlate_Call) RunAndReturn(run func(plate string) (*entity.Vehicle, error)) *MockVehicleRepository_FindByPlate_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockVehicleRepository
func (_mock *MockVehicleRepository) Update(vehicle *entity.Vehicle) error {
	ret := _mock.Called(vehicle)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*entity.Vehicle) error); ok {
		r0 = returnFunc(vehicle)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVehicleRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockVehicleRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - vehicle *entity.Vehicle
func (_e *MockVehicleRepository_Expecter) Update(vehicle interface{}) *MockVehicleRepository_Update_Call {
	return &MockVehicleRepository_Update_Call{Call: _e.mock.On("Update", vehicle)}
}

func (_c *MockVehicleRepository_Update_Call) Run(run func(vehicle *entity.Vehicle)) *MockVehicleRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entity.Vehicle
		if args[0] != nil {
			arg0 = args[0].(*entity.Vehicle)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVehicleRepository_Update_Call) Return(err error) *MockVehicleRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVehicleRepository_Update_Call) RunAndReturn(run func(vehicle *entity.Vehicle) error) *MockVehicleRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
