// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/gabrielcamargo/oficina-api/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockServiceOrderRepository creates a new instance of MockServiceOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceOrderRepository {
	mock := &MockServiceOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServiceOrderRepository is an autogenerated mock type for the ServiceOrderRepository type
type MockServiceOrderRepository struct {
	mock.Mock
}

type MockServiceOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceOrderRepository) EXPECT() *MockServiceOrderRepository_Expecter {
	return &MockServiceOrderRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockServiceOrderRepository
func (_mock *MockServiceOrderRepository) Create(order *entity.ServiceOrder) error {
	ret := _mock.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*entity.ServiceOrder) error); ok {
		r0 = returnFunc(order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceOrderRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockServiceOrderRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - order *entity.ServiceOrder
func (_e *MockServiceOrderRepository_Expecter) Create(order interface{}) *MockServiceOrderRepository_Create_Call {
	return &MockServiceOrderRepository_Create_Call{Call: _e.mock.On("Create", order)}
}

func (_c *MockServiceOrderRepository_Create_Call) Run(run func(order *entity.ServiceOrder)) *MockServiceOrderRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entity.ServiceOrder
		if args[0] != nil {
			arg0 = args[0].(*entity.ServiceOrder)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServiceOrderRepository_Create_Call) Return(err error) *MockServiceOrderRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceOrderRepository_Create_Call) RunAndReturn(run func(order *entity.ServiceOrder) error) *MockServiceOrderRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockServiceOrderRepository
func (_mock *MockServiceOrderRepository) FindAll() ([]*entity.ServiceOrder, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*entity.ServiceOrder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*entity.ServiceOrder, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*entity.ServiceOrder); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.ServiceOrder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceOrderRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockServiceOrderRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *MockServiceOrderRepository_Expecter) FindAll() *MockServiceOrderRepository_FindAll_Call {
	return &MockServiceOrderRepository_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *MockServiceOrderRepository_FindAll_Call) Run(run func()) *MockServiceOrderRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServiceOrderRepository_FindAll_Call) Return(serviceOrders []*entity.ServiceOrder, err error) *MockServiceOrderRepository_FindAll_Call {
	_c.Call.Return(serviceOrders, err)
	return _c
}

func (_c *MockServiceOrderRepository_FindAll_Call) RunAndReturn(run func() ([]*entity.ServiceOrder, error)) *MockServiceOrderRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockServiceOrderRepository
func (_mock *MockServiceOrderRepository) FindByID(id string) (*entity.ServiceOrder, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.ServiceOrder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*entity.ServiceOrder, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *entity.ServiceOrder); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ServiceOrder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceOrderRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockServiceOrderRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id string
func (_e *MockServiceOrderRepository_Expecter) FindByID(id interface{}) *MockServiceOrderRepository_FindByID_Call {
	return &MockServiceOrderRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockServiceOrderRepository_FindByID_Call) Run(run func(id string)) *MockServiceOrderRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServiceOrderRepository_FindByID_Call) Return(serviceOrder *entity.ServiceOrder, err error) *MockServiceOrderRepository_FindByID_Call {
	_c.Call.Return(serviceOrder, err)
	return _c
}

func (_c *MockServiceOrderRepository_FindByID_Call) RunAndReturn(run func(id string) (*entity.ServiceOrder, error)) *MockServiceOrderRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockServiceOrderRepository
func (_mock *MockServiceOrderRepository) Update(order *entity.ServiceOrder) error {
	ret := _mock.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*entity.ServiceOrder) error); ok {
		r0 = returnFunc(order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceOrderRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockServiceOrderRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - order *entity.ServiceOrder
func (_e *MockServiceOrderRepository_Expecter) Update(order interface{}) *MockServiceOrderRepository_Update_Call {
	return &MockServiceOrderRepository_Update_Call{Call: _e.mock.On("Update", order)}
}

func (_c *MockServiceOrderRepository_Update_Call) Run(run func(order *entity.ServiceOrder)) *MockServiceOrderRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entity.ServiceOrder
		if args[0] != nil {
			arg0 = args[0].(*entity.ServiceOrder)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServiceOrderRepository_Update_Call) Return(err error) *MockServiceOrderRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceOrderRepository_Update_Call) RunAndReturn(run func(order *entity.ServiceOrder) error) *MockServiceOrderRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
