// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/gabrielcamargo/oficina-api/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCustomerRepository creates a new instance of MockCustomerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCustomerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCustomerRepository {
	mock := &MockCustomerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCustomerRepository is an autogenerated mock type for the CustomerRepository type
type MockCustomerRepository struct {
	mock.Mock
}

type MockCustomerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCustomerRepository) EXPECT() *MockCustomerRepository_Expecter {
	return &MockCustomerRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockCustomerRepository
func (_mock *MockCustomerRepository) Create(customer *entity.Customer) error {
	ret := _mock.Called(customer)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*entity.Customer) error); ok {
		r0 = returnFunc(customer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCustomerRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCustomerRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - customer *entity.Customer
func (_e *MockCustomerRepository_Expecter) Create(customer interface{}) *MockCustomerRepository_Create_Call {
	return &MockCustomerRepository_Create_Call{Call: _e.mock.On("Create", customer)}
}

func (_c *MockCustomerRepository_Create_Call) Run(run func(customer *entity.Customer)) *MockCustomerRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entity.Customer
		if args[0] != nil {
			arg0 = args[0].(*entity.Customer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCustomerRepository_Create_Call) Return(err error) *MockCustomerRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCustomerRepository_Create_Call) RunAndReturn(run func(customer *entity.Customer) error) *MockCustomerRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockCustomerRepository
func (_mock *MockCustomerRepository) Delete(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCustomerRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCustomerRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id string
func (_e *MockCustomerRepository_Expecter) Delete(id interface{}) *MockCustomerRepository_Delete_Call {
	return &MockCustomerRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockCustomerRepository_Delete_Call) Run(run func(id string)) *MockCustomerRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCustomerRepository_Delete_Call) Return(err error) *MockCustomerRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCustomerRepository_Delete_Call) RunAndReturn(run func(id string) error) *MockCustomerRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockCustomerRepository
func (_mock *MockCustomerRepository) FindAll() ([]*entity.Customer, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*entity.Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*entity.Customer, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*entity.Customer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Customer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomerRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockCustomerRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *MockCustomerRepository_Expecter) FindAll() *MockCustomerRepository_FindAll_Call {
	return &MockCustomerRepository_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *MockCustomerRepository_FindAll_Call) Run(run func()) *MockCustomerRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCustomerRepository_FindAll_Call) Return(customers []*entity.Customer, err error) *MockCustomerRepository_FindAll_Call {
	_c.Call.Return(customers, err)
	return _c
}

func (_c *MockCustomerRepository_FindAll_Call) RunAndReturn(run func() ([]*entity.Customer, error)) *MockCustomerRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByDocument provides a mock function for the type MockCustomerRepository
func (_mock *MockCustomerRepository) FindByDocument(document string) (*entity.Customer, error) {
	ret := _mock.Called(document)

	if len(ret) == 0 {
		panic("no return value specified for FindByDocument")
	}

	var r0 *entity.Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*entity.Customer, error)); ok {
		return returnFunc(document)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *entity.Customer); ok {
		r0 = returnFunc(document)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Customer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(document)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomerRepository_FindByDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByDocument'
type MockCustomerRepository_FindByDocument_Call struct {
	*mock.Call
}

// FindByDocument is a helper method to define mock.On call
//   - document string
func (_e *MockCustomerRepository_Expecter) FindByDocument(document interface{}) *MockCustomerRepository_FindByDocument_Call {
	return &MockCustomerRepository_FindByDocument_Call{Call: _e.mock.On("FindByDocument", document)}
}

func (_c *MockCustomerRepository_FindByDocument_Call) Run(run func(document string)) *MockCustomerRepository_FindByDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCustomerRepository_FindByDocument_Call) Return(customer *entity.Customer, err error) *MockCustomerRepository_FindByDocument_Call {
	_c.Call.Return(customer, err)
	return _c
}

func (_c *MockCustomerRepository_FindByDocument_Call) RunAndReturn(run func(document string) (*entity.Customer, error)) *MockCustomerRepository_FindByDocument_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockCustomerRepository
func (_mock *MockCustomerRepository) FindByID(id string) (*entity.Customer, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*entity.Customer, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *entity.Customer); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Customer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomerRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockCustomerRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id string
func (_e *MockCustomerRepository_Expecter) FindByID(id interface{}) *MockCustomerRepository_FindByID_Call {
	return &MockCustomerRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockCustomerRepository_FindByID_Call) Run(run func(id string)) *MockCustomerRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCustomerRepository_FindByID_Call) Return(customer *entity.Customer, err error) *MockCustomerRepository_FindByID_Call {
	_c.Call.Return(customer, err)
	return _c
}

func (_c *MockCustomerRepository_FindByID_Call) RunAndReturn(run func(id string) (*entity.Customer, error)) *MockCustomerRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockCustomerRepository
func (_mock *MockCustomerRepository) Update(customer *entity.Customer) error {
	ret := _mock.Called(customer)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*entity.Customer) error); ok {
		r0 = returnFunc(customer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCustomerRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCustomerRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - customer *entity.Customer
func (_e *MockCustomerRepository_Expecter) Update(customer interface{}) *MockCustomerRepository_Update_Call {
	return &MockCustomerRepository_Update_Call{Call: _e.mock.On("Update", customer)}
}

func (_c *MockCustomerRepository_Update_Call) Run(run func(customer *entity.Customer)) *MockCustomerRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entity.Customer
		if args[0] != nil {
			arg0 = args[0].(*entity.Customer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCustomerRepository_Update_Call) Return(err error) *MockCustomerRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCustomerRepository_Update_Call) RunAndReturn(run func(customer *entity.Customer) error) *MockCustomerRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
