// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/gabrielcamargo/oficina-api/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPartRepository creates a new instance of MockPartRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPartRepository {
	mock := &MockPartRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPartRepository is an autogenerated mock type for the PartRepository type
type MockPartRepository struct {
	mock.Mock
}

type MockPartRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPartRepository) EXPECT() *MockPartRepository_Expecter {
	return &MockPartRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockPartRepository
func (_mock *MockPartRepository) Create(part *entity.Part) error {
	ret := _mock.Called(part)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*entity.Part) error); ok {
		r0 = returnFunc(part)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPartRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPartRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - part *entity.Part
func (_e *MockPartRepository_Expecter) Create(part interface{}) *MockPartRepository_Create_Call {
	return &MockPartRepository_Create_Call{Call: _e.mock.On("Create", part)}
}

func (_c *MockPartRepository_Create_Call) Run(run func(part *entity.Part)) *MockPartRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entity.Part
		if args[0] != nil {
			arg0 = args[0].(*entity.Part)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPartRepository_Create_Call) Return(err error) *MockPartRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPartRepository_Create_Call) RunAndReturn(run func(part *entity.Part) error) *MockPartRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockPartRepository
func (_mock *MockPartRepository) Delete(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPartRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPartRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id string
func (_e *MockPartRepository_Expecter) Delete(id interface{}) *MockPartRepository_Delete_Call {
	return &MockPartRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockPartRepository_Delete_Call) Run(run func(id string)) *MockPartRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPartRepository_Delete_Call) Return(err error) *MockPartRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPartRepository_Delete_Call) RunAndReturn(run func(id string) error) *MockPartRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockPartRepository
func (_mock *MockPartRepository) FindAll() ([]*entity.Part, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*entity.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*entity.Part, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*entity.Part); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPartRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockPartRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *MockPartRepository_Expecter) FindAll() *MockPartRepository_FindAll_Call {
	return &MockPartRepository_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *MockPartRepository_FindAll_Call) Run(run func()) *MockPartRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPartRepository_FindAll_Call) Return(parts []*entity.Part, err error) *MockPartRepository_FindAll_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *MockPartRepository_FindAll_Call) RunAndReturn(run func() ([]*entity.Part, error)) *MockPartRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockPartRepository
func (_mock *MockPartRepository) FindByID(id string) (*entity.Part, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*entity.Part, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *entity.Part); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPartRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockPartRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id string
func (_e *MockPartRepository_Expecter) FindByID(id interface{}) *MockPartRepository_FindByID_Call {
	return &MockPartRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockPartRepository_FindByID_Call) Run(run func(id string)) *MockPartRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPartRepository_FindByID_Call) Return(part *entity.Part, err error) *MockPartRepository_FindByID_Call {
	_c.Call.Return(part, err)
	return _c
}

func (_c *MockPartRepository_FindByID_Call) RunAndReturn(run func(id string) (*entity.Part, error)) *MockPartRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockPartRepository
func (_mock *MockPartRepository) Update(part *entity.Part) error {
	ret := _mock.Called(part)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*entity.Part) error); ok {
		r0 = returnFunc(part)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPartRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPartRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - part *entity.Part
func (_e *MockPartRepository_Expecter) Update(part interface{}) *MockPartRepository_Update_Call {
	return &MockPartRepository_Update_Call{Call: _e.mock.On("Update", part)}
}

func (_c *MockPartRepository_Update_Call) Run(run func(part *entity.Part)) *MockPartRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entity.Part
		if args[0] != nil {
			arg0 = args[0].(*entity.Part)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPartRepository_Update_Call) Return(err error) *MockPartRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPartRepository_Update_Call) RunAndReturn(run func(part *entity.Part) error) *MockPartRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
