// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/gabrielcamargo/oficina-api/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockServiceRepository creates a new instance of MockServiceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceRepository {
	mock := &MockServiceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServiceRepository is an autogenerated mock type for the ServiceRepository type
type MockServiceRepository struct {
	mock.Mock
}

type MockServiceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceRepository) EXPECT() *MockServiceRepository_Expecter {
	return &MockServiceRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockServiceRepository
func (_mock *MockServiceRepository) Create(service *entity.Service) error {
	ret := _mock.Called(service)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*entity.Service) error); ok {
		r0 = returnFunc(service)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockServiceRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - service *entity.Service
func (_e *MockServiceRepository_Expecter) Create(service interface{}) *MockServiceRepository_Create_Call {
	return &MockServiceRepository_Create_Call{Call: _e.mock.On("Create", service)}
}

func (_c *MockServiceRepository_Create_Call) Run(run func(service *entity.Service)) *MockServiceRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entity.Service
		if args[0] != nil {
			arg0 = args[0].(*entity.Service)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServiceRepository_Create_Call) Return(err error) *MockServiceRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceRepository_Create_Call) RunAndReturn(run func(service *entity.Service) error) *MockServiceRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockServiceRepository
func (_mock *MockServiceRepository) Delete(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockServiceRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id string
func (_e *MockServiceRepository_Expecter) Delete(id interface{}) *MockServiceRepository_Delete_Call {
	return &MockServiceRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockServiceRepository_Delete_Call) Run(run func(id string)) *MockServiceRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServiceRepository_Delete_Call) Return(err error) *MockServiceRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceRepository_Delete_Call) RunAndReturn(run func(id string) error) *MockServiceRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockServiceRepository
func (_mock *MockServiceRepository) FindAll() ([]*entity.Service, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*entity.Service
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*entity.Service, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*entity.Service); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Service)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockServiceRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *MockServiceRepository_Expecter) FindAll() *MockServiceRepository_FindAll_Call {
	return &MockServiceRepository_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *MockServiceRepository_FindAll_Call) Run(run func()) *MockServiceRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServiceRepository_FindAll_Call) Return(services []*entity.Service, err error) *MockServiceRepository_FindAll_Call {
	_c.Call.Return(services, err)
	return _c
}

func (_c *MockServiceRepository_FindAll_Call) RunAndReturn(run func() ([]*entity.Service, error)) *MockServiceRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockServiceRepository
func (_mock *MockServiceRepository) FindByID(id string) (*entity.Service, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Service
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*entity.Service, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *entity.Service); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Service)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockServiceRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id string
func (_e *MockServiceRepository_Expecter) FindByID(id interface{}) *MockServiceRepository_FindByID_Call {
	return &MockServiceRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockServiceRepository_FindByID_Call) Run(run func(id string)) *MockServiceRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServiceRepository_FindByID_Call) Return(service *entity.Service, err error) *MockServiceRepository_FindByID_Call {
	_c.Call.Return(service, err)
	return _c
}

func (_c *MockServiceRepository_FindByID_Call) RunAndReturn(run func(id string) (*entity.Service, error)) *MockServiceRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockServiceRepository
func (_mock *MockServiceRepository) Update(service *entity.Service) error {
	ret := _mock.Called(service)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*entity.Service) error); ok {
		r0 = returnFunc(service)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockServiceRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - service *entity.Service
func (_e *MockServiceRepository_Expecter) Update(service interface{}) *MockServiceRepository_Update_Call {
	return &MockServiceRepository_Update_Call{Call: _e.mock.On("Update", service)}
}

func (_c *MockServiceRepository_Update_Call) Run(run func(service *entity.Service)) *MockServiceRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entity.Service
		if args[0] != nil {
			arg0 = args[0].(*entity.Service)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServiceRepository_Update_Call) Return(err error) *MockServiceRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceRepository_Update_Call) RunAndReturn(run func(service *entity.Service) error) *MockServiceRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
