// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/gabrielcamargo/oficina-api/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNotificationService creates a new instance of MockNotificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationService {
	mock := &MockNotificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotificationService is an autogenerated mock type for the NotificationService type
type MockNotificationService struct {
	mock.Mock
}

type MockNotificationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationService) EXPECT() *MockNotificationService_Expecter {
	return &MockNotificationService_Expecter{mock: &_m.Mock}
}

// NotifyOrderStatusChanged provides a mock function for the type MockNotificationService
func (_mock *MockNotificationService) NotifyOrderStatusChanged(customer *entity.Customer, order *entity.ServiceOrder) error {
	ret := _mock.Called(customer, order)

	if len(ret) == 0 {
		panic("no return value specified for NotifyOrderStatusChanged")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*entity.Customer, *entity.ServiceOrder) error); ok {
		r0 = returnFunc(customer, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationService_NotifyOrderStatusChanged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyOrderStatusChanged'
type MockNotificationService_NotifyOrderStatusChanged_Call struct {
	*mock.Call
}

// NotifyOrderStatusChanged is a helper method to define mock.On call
//   - customer *entity.Customer
//   - order *entity.ServiceOrder
func (_e *MockNotificationService_Expecter) NotifyOrderStatusChanged(customer interface{}, order interface{}) *MockNotificationService_NotifyOrderStatusChanged_Call {
	return &MockNotificationService_NotifyOrderStatusChanged_Call{Call: _e.mock.On("NotifyOrderStatusChanged", customer, order)}
}

func (_c *MockNotificationService_NotifyOrderStatusChanged_Call) Run(run func(customer *entity.Customer, order *entity.ServiceOrder)) *MockNotificationService_NotifyOrderStatusChanged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entity.Customer
		if args[0] != nil {
			arg0 = args[0].(*entity.Customer)
		}
		var arg1 *entity.ServiceOrder
		if args[1] != nil {
			arg1 = args[1].(*entity.ServiceOrder)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationService_NotifyOrderStatusChanged_Call) Return(err error) *MockNotificationService_NotifyOrderStatusChanged_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationService_NotifyOrderStatusChanged_Call) RunAndReturn(run func(customer *entity.Customer, order *entity.ServiceOrder) error) *MockNotificationService_NotifyOrderStatusChanged_Call {
	_c.Call.Return(run)
	return _c
}
