// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/gabrielcamargo/oficina-api/internal/domain/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCNPJValidationService creates a new instance of MockCNPJValidationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCNPJValidationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCNPJValidationService {
	mock := &MockCNPJValidationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCNPJValidationService is an autogenerated mock type for the CNPJValidationService type
type MockCNPJValidationService struct {
	mock.Mock
}

type MockCNPJValidationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCNPJValidationService) EXPECT() *MockCNPJValidationService_Expecter {
	return &MockCNPJValidationService_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function for the type MockCNPJValidationService
func (_mock *MockCNPJValidationService) Fetch(cnpj string) (*repository.CNPJInfo, error) {
	ret := _mock.Called(cnpj)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 *repository.CNPJInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*repository.CNPJInfo, error)); ok {
		return returnFunc(cnpj)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *repository.CNPJInfo); ok {
		r0 = returnFunc(cnpj)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.CNPJInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(cnpj)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCNPJValidationService_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockCNPJValidationService_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - cnpj string
func (_e *MockCNPJValidationService_Expecter) Fetch(cnpj interface{}) *MockCNPJValidationService_Fetch_Call {
	return &MockCNPJValidationService_Fetch_Call{Call: _e.mock.On("Fetch", cnpj)}
}

func (_c *MockCNPJValidationService_Fetch_Call) Run(run func(cnpj string)) *MockCNPJValidationService_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCNPJValidationService_Fetch_Call) Return(cNPJInfo *repository.CNPJInfo, err error) *MockCNPJValidationService_Fetch_Call {
	_c.Call.Return(cNPJInfo, err)
	return _c
}

func (_c *MockCNPJValidationService_Fetch_Call) RunAndReturn(run func(cnpj string) (*repository.CNPJInfo, error)) *MockCNPJValidationService_Fetch_Call {
	_c.Call.Return(run)
	return _c
}
